name: Deploy to Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Deploy to Surge.sh
        run: npx surge dist/ react-video-editor-fix-v3.surge.sh --token 9d3b4ee409a48af28e6c3afdfb50d5af
